name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: generate build system
      run:  cmake -Bbuild
    - name: build and test
      run:  |
            cd build
            cmake --build .
            ctest
