name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Generate the build system
      run:  cmake -DBUILD_DOC=OFF -DENABLE_FORMAT=OFF -Bbuild
    - name: Build and Test
      run:  |
            cd build
            cmake --build .
            ctest -C Debug
