name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run:  sudo apt-get install doxygen graphviz -y
    - name: Generate the build system
      run:  cmake -Bbuild
    - name: Build and Test
      run:  |
            cd build
            cmake --build .
            ctest
